### PR TITLE
Removed copy-webpack-plugin dependency

### PR DESCRIPTION
**Pull request by juspky**
Works in IE!!!
Ignore the errors, thats something else
grafik

### CODE REVIEW

**Comment by olmobrutall** [comment]
Promises too? They have updated IE?

**Comment by juspky** [comment]
No, the polyfills are loaded in entry instead of being copied later

**Comment by olmobrutall** [comment]
Oh, I see. But then a better approach will be to add the polyfils in vendor.js. 

Could you try this pleeeeease :D

**Comment by olmobrutall** [comment]
This file also needs changes https://github.com/signumsoftware/southwind/blob/master/Southwind.React/Views/Home/Index.cshtml

**Comment by juspky** [comment]
Don't merge this yet
I just realized that the polyfills were still in dist folder and Index.cshtml imported it.

**Comment by juspky** [comment]
Goodbye vendor.js
https://webpack.js.org/concepts/entry-points/#separate-app-and-vendor-entries

Webpack does this by default
https://webpack.js.org/plugins/split-chunks-plugin/#configuration

I'll do this

**Comment by juspky** [comment]
-> https://github.com/signumsoftware/southwind/pull/8

**Pull request closed without merging**
